### Import Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_excel('customer_service_chatbot_dataset_v2.xlsx')

In [3]:
dataset

,user_query,intent,response
0,Hi,greeting,Hello! What can I do for you?
1,Loved your product,feedback,Your feedback helps us improve. Thanks for sha...
2,Hello,greeting,Hello! What can I do for you?
3,I want to file a complaint,complaint,Please provide your order ID to file a complaint.
4,I can’t log in,technical_issue,Try restarting the app and see if the issue pe...
...,...,...,...
995,Great service!,feedback,Your feedback helps us improve. Thanks for sha...
996,Please start my return process,return_request,"Sure, please share your order ID to initiate t..."
997,I can’t log in,technical_issue,We’re working on fixing this technical glitch....
998,How can I return my product?,refund_request,Please share your payment details to start the...
999,What’s the warranty?,product_info,This product comes with a one-year warranty.

In [4]:
dataset.shape

(1000, 3)

### NLP

In [5]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [6]:
ps = WordNetLemmatizer()

In [7]:
stopwords = stopwords.words('english')

In [8]:
def clean_row(row):

    row = row.lower()
    row = re.sub('[^a-zA-Z]', '', row)
    
    token = row.split()
    
    Issue = [ps.lemmatize(word) for word in token if not word in stopwords]
    
    cleaned_Issue = ' '.join(Issue)
    
    return cleaned_Issue

In [9]:
dataset['user_query']

0                                  Hi
1                  Loved your product
2                               Hello
3          I want to file a complaint
4                      I can’t log in
                    ...
995                    Great service!
996    Please start my return process
997                    I can’t log in
998      How can I return my product?
999              What’s the warranty?
Name: user_query, Length: 1000, dtype: object

In [10]:
dataset['user_query'] = dataset['user_query'].apply(lambda x : clean_row(x))

In [11]:
dataset['user_query']

0                              hi
1                lovedyourproduct
2                           hello
3           iwanttofileacomplaint
4                      icantlogin
                  ...
995                  greatservice
996    pleasestartmyreturnprocess
997                    icantlogin
998        howcanireturnmyproduct
999              whatsthewarranty
Name: user_query, Length: 1000, dtype: object

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [13]:
vectorizer = TfidfVectorizer(max_features=3000, lowercase=False, ngram_range=(1,2))

In [14]:
x = dataset['user_query']
y = dataset['intent']

In [15]:
x

0                              hi
1                lovedyourproduct
2                           hello
3           iwanttofileacomplaint
4                      icantlogin
                  ...
995                  greatservice
996    pleasestartmyreturnprocess
997                    icantlogin
998        howcanireturnmyproduct
999              whatsthewarranty
Name: user_query, Length: 1000, dtype: object

In [16]:
y

0             greeting
1             feedback
2             greeting
3            complaint
4      technical_issue
            ...
995           feedback
996     return_request
997    technical_issue
998     refund_request
999       product_info
Name: intent, Length: 1000, dtype: object

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [19]:
vec_x_train = vectorizer.fit_transform(x_train)

In [20]:
vec_x_train = vec_x_train.toarray()

In [21]:
type(vec_x_train)

numpy.ndarray

In [22]:
vec_x_test = vectorizer.transform(x_test)

In [23]:
vec_x_test = vec_x_test.toarray()

In [24]:
vec_x_train.shape,vec_x_test.shape

((800, 41), (200, 41))

In [25]:
vec_x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
vec_x_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [27]:
training_data = pd.DataFrame(vec_x_train,columns = vectorizer.get_feature_names_out())
testing_data = pd.DataFrame(vec_x_test,columns = vectorizer.get_feature_names_out())

In [28]:
training_data

,appiscrashing,bye,goodbye,goodevening,goodmorning,greatservice,hasmypackagebeenshipped,havingissueswithpayment,hello,heythere,...,tellmeaboutthisproduct,thanks,thatsall,theresatechnicalproblem,trackmyorder,websitenotloading,whatsthewarranty,whenwillireceivemydelivery,whereismyorder,youshouldimprovedelivery
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
796,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
797,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
799,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
testing_data

,appiscrashing,bye,goodbye,goodevening,goodmorning,greatservice,hasmypackagebeenshipped,havingissueswithpayment,hello,heythere,...,tellmeaboutthisproduct,thanks,thatsall,theresatechnicalproblem,trackmyorder,websitenotloading,whatsthewarranty,whenwillireceivemydelivery,whereismyorder,youshouldimprovedelivery
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
196,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
198,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
199,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

### Model

In [30]:
from sklearn.naive_bayes import MultinomialNB

In [31]:
clf = MultinomialNB()

In [32]:
clf.fit(vec_x_train, y_train)

MultinomialNB()

In [33]:
import warnings
warnings.filterwarnings("ignore", message="X has feature names")

In [34]:
y_pred = clf.predict(testing_data)

In [35]:
y_pred

array(['order_status', 'return_request', 'return_request',
       'refund_request', 'closing', 'refund_request', 'return_request',
       'return_request', 'product_info', 'refund_request', 'product_info',
       'return_request', 'product_info', 'greeting', 'greeting',
       'refund_request', 'complaint', 'closing', 'refund_request',
       'order_status', 'feedback', 'complaint', 'feedback', 'complaint',
       'feedback', 'refund_request', 'return_request', 'payment_issue',
       'technical_issue', 'complaint', 'product_info', 'feedback',
       'order_status', 'technical_issue', 'complaint', 'complaint',
       'payment_issue', 'return_request', 'refund_request', 'feedback',
       'payment_issue', 'technical_issue', 'complaint', 'feedback',
       'order_status', 'payment_issue', 'greeting', 'return_request',
       'greeting', 'payment_issue', 'greeting', 'payment_issue',
       'closing', 'refund_request', 'refund_request', 'payment_issue',
       'closing', 'product_info', 'greeting', 'return_request',
       'payment_issue', 'return_request', 'return_request',
       'order_status', 'greeting', 'product_info', 'complaint',
       'technical_issue', 'payment_issue', 'order_status',
       'return_request', 'feedback', 'technical_issue', 'refund_request',
       'order_status', 'complaint', 'technical_issue', 'product_info',
       'complaint', 'closing', 'greeting', 'greeting', 'closing',
       'product_info', 'technical_issue', 'complaint', 'refund_request',
       'complaint', 'closing', 'order_status', 'return_request',
       'product_info', 'product_info', 'complaint', 'feedback',
       'technical_issue', 'return_request', 'feedback', 'greeting',
       'greeting', 'closing', 'return_request', 'return_request',
       'closing', 'feedback', 'greeting', 'feedback', 'refund_request',
       'complaint', 'order_status', 'return_request', 'product_info',
       'order_status', 'technical_issue', 'greeting', 'complaint',
       'return_request', 'greeting', 'product_info', 'return_request',
       'greeting', 'refund_request', 'refund_request', 'technical_issue',
       'closing', 'product_info', 'complaint', 'feedback',
       'return_request', 'return_request', 'return_request', 'feedback',
       'greeting', 'feedback', 'order_status', 'product_info', 'feedback',
       'product_info', 'payment_issue', 'closing', 'feedback',
       'return_request', 'product_info', 'order_status', 'feedback',
       'refund_request', 'order_status', 'closing', 'order_status',
       'product_info', 'return_request', 'refund_request',
       'return_request', 'feedback', 'product_info', 'closing', 'closing',
       'order_status', 'technical_issue', 'order_status',
       'return_request', 'feedback', 'technical_issue', 'greeting',
       'return_request', 'closing', 'feedback', 'return_request',
       'product_info', 'order_status', 'product_info', 'return_request',
       'closing', 'order_status', 'greeting', 'feedback', 'product_info',
       'payment_issue', 'product_info', 'greeting', 'payment_issue',
       'product_info', 'payment_issue', 'complaint', 'order_status',
       'feedback', 'closing', 'payment_issue', 'closing', 'payment_issue',
       'refund_request', 'feedback', 'refund_request', 'feedback',
       'return_request', 'product_info', 'return_request',
       'refund_request', 'product_info', 'product_info'], dtype='<U15')

In [36]:
y_test

521      order_status
737    return_request
740    return_request
660    refund_request
411           closing
            ...
408      product_info
332    return_request
208    refund_request
613      product_info
78       product_info
Name: intent, Length: 200, dtype: object

### Confusion Matrix and Accuracy

In [37]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [38]:
confusion_matrix(y_test,y_pred)

array([[18,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 17,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 24,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 19,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 19,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 15,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 26,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 19,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 31,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 12]])

In [39]:
accuracy_score(y_test,y_pred)

1.0

In [40]:
y_pred_train = clf.predict(vec_x_train)

In [41]:
accuracy_score(y_train,y_pred_train)

1.0

### Sample Example of Testing Data

In [42]:
User_Query = input("Enter query: ")

response = clean_row(str(User_Query))

pred = clf.predict(vectorizer.transform([response]).toarray())[0]

if pred:
    reply = dataset[dataset['intent'] == pred]['response'].sample(1).values[0]
    print(f"\nPredicted Intent: {pred}")
    print(f"Chatbot Response: {reply}")
else:
    print("Not Found Any Response")

Enter query:  hi

Predicted Intent: greeting
Chatbot Response: Hi there! How can I help you today?